export const ALL_NEWS_REQUEST = "ALL_NEWS_REQUEST";
export const ALL_NEWS_SUCCESS = "ALL_NEWS_SUCCESS";
export const ALL_NEWS_FAILURE = "ALL_NEWS_FAILURE";

export const ONE_NEWS_REQUEST = "ONE_NEWS_REQUEST";
export const ONE_NEWS_SUCCESS = "ONE_NEWS_SUCCESS";
export const ONE_NEWS_FAILURE = "ONE_NEWS_FAILURE";

export const CURRENT_NEWS_REQUEST = "CURRENT_NEWS_REQUEST";
export const CURRENT_NEWS_SUCCESS = "CURRENT_NEWS_SUCCESS";
export const CURRENT_NEWS_FAILURE = "CURRENT_NEWS_FAILURE";

export const CREATE_NEWS_REQUEST = "CREATE_NEWS_REQUEST";
export const CREATE_NEWS_SUCCESS = "CREATE_NEWS_SUCCESS";
export const CREATE_NEWS_FAILURE = "CREATE_NEWS_FAILURE";

export const UPDATE_NEWS_REQUEST = "UPDATE_NEWS_REQUEST";
export const UPDATE_NEWS_SUCCESS = "UPDATE_NEWS_SUCCESS";
export const UPDATE_NEWS_FAILURE = "UPDATE_NEWS_FAILURE";

export const DELETE_NEWS_REQUEST = "DELETE_NEWS_REQUEST";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_FAILURE = "DELETE_NEWS_FAILURE";
